import type { Metadata } from "next";
import Providers from "../components/Providers";
import Sidebar from "../components/SideBar";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   
      <div>
      <Providers>
      
          <div className="flex h-full">
            {/* Sidebar */}
            <Sidebar />
            
            {/* Main content area */}
            <div className="flex flex-1 justify-center items-center p-4">
              {children}
            </div>
          </div>
    
      </Providers>
      </div>
 
  );
}
